### ISSUE TITLE
Text link

### ISSUE THREAD

**Issue by wernerlaude** [postare/bulma-modal-fx#6]
Thanks for your work.
Would be great to also supply a text link trigger the modal.
Buttons are not always the best solution..

**Comment by diomed** [comment]
doesn't matter which element you use it on; 
as long as it has that class, and data-target, of course:

`<a href="#" class="modal-button"  data-target="modal-image">modal examples</a>`

I even use it on images;
`                <img src="https://source.unsplash.com/hLyd1LukQ7E" alt="butterfly image" class="modal-button" data-target="modal-image4">
`

**Comment by wernerlaude** [comment]
Thanks.. great..

> Am 19.09.2018 um 22:01 schrieb May Kittens Devour Your Soul <notifications@github.com>:
> 
> <a href="#" class="modal-button" data-target="modal-image">modal examples</a>

Werner Laude - WebDevelopment - München 
mail@laude.biz <mailto:mail@laude.biz> | +49 178 135 34 39 <tel:+49 178 135 34 39>
